[theme]
base = "dark"                           
primaryColor = "#22c55e"                # accent
backgroundColor = "#0b1220"
secondaryBackgroundColor = "#0f172a"
textColor = "#e5e7eb"
font = "sans serif"                     # "serif" | "monospace" | "sans serif"
